export enum ECities {
  Kyiv = "Kyiv",
  Kharkiv = "Kharkiv",
  Dnipro = "Dnipro",
  Odesa = "Odesa",
  Lviv = "Lviv",
  Zaporizhzhia = "Zaporizhzhia",
  IvanoFrankivsk = "Ivano-Frankivsk",
  Vinnytsia = "Vinnytsia",
  Uzhhorod = "Uzhhorod",
  Ternopil = "Ternopil",
  Lutsk = "Lutsk",
  Rivne = "Rivne",
  Chernivtsi = "Chernivtsi",
  Sumy = "Sumy",
  Poltava = "Poltava",
  Mykolaiv = "Mykolaiv",
  Chernihiv = "Chernihiv",
  Kherson = "Kherson",
  Khmelnytskyi = "Khmelnytskyi",
  Kropyvnytskyi = "Kropyvnytskyi",
  Cherkasy = "Cherkasy",
}
