import { config } from "dotenv";

config();

const {
  MONGO_INITDB_ROOT_USERNAME,
  MONGO_INITDB_ROOT_PASSWORD,
  MONGO_INITDB_DATABASE,
  DB_HOST,
  DB_PORT,
} = process.env;

export const configs = {
  DB_URI: `mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DB_HOST}:${DB_PORT}/${MONGO_INITDB_DATABASE}`,
  PORT: process.env.PORT,

  FRONT_URL: process.env.FRONT_URL,

  SECRET_SALT: +process.env.SECRET_SALT,

  SECRET_USER_ACCESS_KEY: process.env.SECRET_USER_ACCESS_KEY,
  SECRET_USER_REFRESH_KEY: process.env.SECRET_USER_REFRESH_KEY,
  JWT_USER_ACCESS_EXPIRES_IN: process.env.JWT_USER_ACCESS_EXPIRES_IN,
  JWT_USER_REFRESH_EXPIRES_IN: process.env.JWT_USER_REFRESH_EXPIRES_IN,

  SECRET_ADMIN_ACCESS_KEY: process.env.SECRET_ADMIN_ACCESS_KEY,
  SECRET_ADMIN_REFRESH_KEY: process.env.SECRET_ADMIN_REFRESH_KEY,
  JWT_ADMIN_ACCESS_EXPIRES_IN: process.env.JWT_ADMIN_ACCESS_EXPIRES_IN,
  JWT_ADMIN_REFRESH_EXPIRES_IN: process.env.JWT_ADMIN_REFRESH_EXPIRES_IN,

  SECRET_ACTION_KEY: process.env.SECRET_ACTION_KEY,
  SECRET_ACTIVATE_ACTION_KEY: process.env.SECRET_ACTIVATE_ACTION_KEY,
  JWT_ACTION_TOKEN_EXPIRES_IN: process.env.JWT_ACTION_TOKEN_EXPIRES_IN,

  NO_REPLY_EMAIL: process.env.NO_REPLY_EMAIL,
  NO_REPLY_PASSWORD: process.env.NO_REPLY_PASSWORD,

  AWS_S3_ACCESS_KEY: process.env.AWS_S3_ACCESS_KEY,
  AWS_S3_SECRET_KEY: process.env.AWS_S3_SECRET_KEY,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: process.env.AWS_S3_REGION,
  AWS_S3_URL: process.env.AWS_S3_URL,
};
